version: "3.5"

services:
  app:
    build:
      context: /Users/dauren/GolandProjects/SDP/server/src
      dockerfile: /Users/dauren/GolandProjects/SDP/server/src/Dockerfile
    container_name: sdp-backend
    depends_on:
      - postgres
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
    volumes:
      - "./config.json:/opt/sdp/config.json"
    restart: always
    networks:
      - proxy
      - default

  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: sdp-proxy
    restart: always
    #command: rm /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /Users/dauren/GolandProjects/SDP/infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  proxy:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: